schema_config:
  schema_dir: config
  schema_file: schema.yaml

training_pipeline_config:
  pipeline: Sales_Forecasting_Artifact
  artifact_dir: Artifact

data_ingestion_config:
  dataset_download_url : https://github.com/sumeet0701/data-dump/blob/main/outlier_clean.zip?raw=true
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test

data_validation_config:
  data_validation: data_validation
  validation_dir: validated_data

data_transformation_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  time_series_data: time_series_data
  feature_engineering_object_file_name: feat_eng.pkl
  preprocessed_object_file_name: preprocessed.pkl


model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  model_config_dir: config
  model_config_file_name: model.yaml
  prediction_rows: 100


model_trainer_time_config:
  trained_model_dir: trained_time_model
  model_file_name: model.pkl
  model_config_dir: config
  model_report_file_name: model.yaml
  prediction_image: prediction.png
  time_model_file_name: 'grouped_data.csv'
  prediction_rows: 100

data_base:
 data_base_name: Sales
 collection_name: data